# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ec4390410a13b96b669a80b1931e29537f3f577e17c89500055bd4a2b7ace288f25590a468ad5fd707c2d84c810aad092f42729902c7855dd5ff8c5fc20d8167

test:
  secret_key_base: 2967f2974e80c1d0fb856d8385e1c45dada1763c8401920fbb5f1311d214fec28d63fecca2a0c069821be092db5efd1cd677897392e5572754fb8d9664fff0fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
